### ISSUE TITLE
Dependency compatibility issue

### ISSUE THREAD

**Issue by hugovdev** [WildMeOrg/wildbook-ia#208]
"wbia" command won't work even after correctly installing everything without errors. (It doesn't recognize it)
"wbia-" commands do get installed correctly some times

**Comment by hugovdev** [comment]
I'm using Ubuntu Desktop 20.04

**Comment by hugovdev** [comment]
![image](https://user-images.githubusercontent.com/23460704/161019730-846f3077-8e3e-4624-bbdb-8fc653b8b73b.png)
There is no way to satisfy both of this requirements...

**Comment by bluemellophone** [comment]
Correct, WBIA is almost exclusively a REST API and web-based UI application.  There still is an old QT interface, but that has been long deprecated and has not been used in almost 4 years.  The original IBEIS project (https://github.com/Erotemic/ibeis) still maintains a working GUI, I believe.

**Comment by hugovdev** [comment]
> Correct, WBIA is almost exclusively a REST API and web-based UI application.  There still is an old QT interface, but that has been long deprecated and has not been used in almost 4 years.  The original IBEIS project (https://github.com/Erotemic/ibeis) still maintains a working GUI, I believe.  

Then, maybe you should update the readme, cause it states "use wbia to open the GUI" 😭

**Comment by bluemellophone** [comment]
You are entirely correct, I will remove that
