### ISSUE TITLE
Contrary to docs index page, Hotspotter binaries are not directly available

### ISSUE THREAD

**Issue by lobrien** [WildMeOrg/wildbook-ia#210]
`docs/index.html` says:

```
The IBEIS toolkit originally was a wrapper around HotSpotter, for which original binaries can be downloaded from: <a class="reference external" href="http://cs.rpi.edu/hotspotter/">http://cs.rpi.edu/hotspotter/</a></p>
```

But visiting that site results in a 403, Unauthorized response. If this is expected behavior, the docs page should be updated to whatever the appropriate advice is: "Contact the maintainer for access," etc.

**Comment by Erotemic** [comment]
Please feel free to rehost the binaries, which can still be accessed via:

* Win32 Installer: https://www.dropbox.com/s/5j1xyx2hq1wzqz2/hotspotter-win32-setup.exe?dl=0 

* OSX Installer: https://www.dropbox.com/s/q0vzz3xnjbxhsda/hotspotter_installer_mac.dmg?dl=0

I've also just uploaded the binaries to IPFS. IPFS CIDs for the previous installers are QmSnyetkniriHUwTxvzwhkysPKjUj7udBqq5mpK24VJXVM and QmZ3WknrAaxPZhZebdQWZ45EEKwu1Tr6bkFWJzfPRtENs7.

IPFS data can be accessed via https using:

https://ipfs.io/ipfs/QmSnyetkniriHUwTxvzwhkysPKjUj7udBqq5mpK24VJXVM 
https://ipfs.io/ipfs/QmZ3WknrAaxPZhZebdQWZ45EEKwu1Tr6bkFWJzfPRtENs7


But as I always say when I mention hotspotter: It has severe limitations and buggy sometimes non-intuitive behavior. If you use it, make sure you back up your data. Using the wildme software is really the right way to go. And if you must use standalone desktop software, getting a linux machine to `pip install ibeis` on Python 3.7 or Python 3.8 is far more reliable.

**Comment by bluemellophone** [comment]
As @Erotemic said, the HotSpotter algorithm is free to download and available at the above links.  I have downloaded these same binaries and have uploaded them to our CDN.  The latest commit c144377516249ac99bfaed51b9ab19e6dd598177 has an updated section of the docs to repeat the information provided above
